services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
      # Apple Silicon GPU acceleration
      - METAL_DEVICE=on
      - METAL_DEVICE_INDEX=0
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    restart: unless-stopped

  hedge-fund:
    build: .
    image: ai-hedge-fund
    depends_on:
      - ollama
    volumes:
      - ./.env:/app/.env
    command: python -m src.main --ticker AAPL,MSFT,NVDA
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
      - OLLAMA_BASE_URL=http://ollama:11434
    tty: true
    stdin_open: true

  hedge-fund-reasoning:
    build: .
    image: ai-hedge-fund
    depends_on:
      - ollama
    volumes:
      - ./.env:/app/.env
    command: python -m src.main --ticker AAPL,MSFT,NVDA --show-reasoning
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
      - OLLAMA_BASE_URL=http://ollama:11434
    tty: true
    stdin_open: true

  hedge-fund-ollama:
    build: .
    image: ai-hedge-fund
    depends_on:
      - ollama
    volumes:
      - ./.env:/app/.env
    command: python -m src.main --ticker AAPL,MSFT,NVDA --ollama
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
      - OLLAMA_BASE_URL=http://ollama:11434
    tty: true
    stdin_open: true

  backtester:
    build: .
    image: ai-hedge-fund
    depends_on:
      - ollama
    volumes:
      - ./.env:/app/.env
    command: python -m src.backtester --ticker AAPL,MSFT,NVDA
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
      - OLLAMA_BASE_URL=http://ollama:11434
    tty: true
    stdin_open: true

  backtester-ollama:
    build: .
    image: ai-hedge-fund
    depends_on:
      - ollama
    volumes:
      - ./.env:/app/.env
    command: python -m src.backtester --ticker AAPL,MSFT,NVDA --ollama
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
      - OLLAMA_BASE_URL=http://ollama:11434
    tty: true
    stdin_open: true

  test-imports:
    build: .
    image: ai-hedge-fund
    volumes:
      - ./.env:/app/.env
    command: python test_imports.py
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
    tty: true
    stdin_open: true
    
  debug-args:
    build: .
    image: ai-hedge-fund
    volumes:
      - ./.env:/app/.env
      - ./debug_args.py:/app/debug_args.py
    command: python debug_args.py
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
    tty: true
    stdin_open: true

volumes:
  ollama_data: 